# Generated by Django 2.1.7 on 2019-04-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20190426_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
